export const ADAPTIVE_TOOL_NAME = 'adaptive_search'
export const ADAPTIVE_DESCRIPTION = 'Bounded fused + Jev screening for ONE full question with a required intent. Write the question and intent in English (a caller instruction only: the server never language-checks, rejects or translates them, and any language is searched exactly as written). Only the original question is searched: no keyword planning, no query expansion, no constraints gate. One pre-search Jev strategy request selects a fixed balanced/research/fresh ranking and, when community is omitted, enable/disable/unknown for the ALREADY wired community (X) branch; an explicit community true/false overrides that choice and is never asked back. Unknown or missing community answers fall back to no community branch and are disclosed; they never widen permissions, engines, credentials or domain limits. The declared fused snapshot (max 32 candidates, community branch included when enabled) is reviewed in size-split batches: fixed safety clear/violation/unavailable, prototype value levels 0-5 and source discounts from real positive-contribution engines. Only safe material with value level 3/4/5 is delivered, ranked by the versioned screening formula; confidence is audit-only. constraints is retired: omit it or pass [] (warning); a non-empty array is refused with adaptive_constraints_removed before any network call - keep the full question and direction in questions/intent. max_results caps the results selected and saved (default 10, max 50); page_size only changes the page (default 20, max 50). Every declared candidate in that snapshot is reviewed before selection - no early stop at the first K acceptable links, and no self-imposed cumulative cost, token, request-count or total-duration quota stops the run (real single-request timeouts, limited retries, authentication/rate-limit failures, safety refusals and explicit cancellation still apply). targetMet means quantity only, never research completion or verification; outsideReview/unreviewed and failed or unavailable judgements are disclosed, not treated as low value. save_results:true privately stores the complete final selected set and returns savedResultId for export/recovery after restart (no credentials or model logs). Cursor s5:/h1: reads saved pages with page_size only: no search, strategy, Jev, community or value call; pages are process-local for 30 minutes / 32 runs, and h1: is a read-only historical snapshot that must not be read as fresh evidence. Requires configured Jev (default TypeSafe or the configured service); question, direction and necessary fragments go there, never engine credentials. Do not send secrets or private reasoning. The main Agent still owns research, decisive reading, verification and the final answer. Use fused_search for direct search, fetch_page for known pages and x_search for X-only material.'
export const ADAPTIVE_PROMPT_GUIDELINES = [
  'Supply exactly one full question and a required intent. English is requested in the description but is never enforced: non-English or mixed-language input runs through the same strategy and original-text search.',
  'community is optional: omit it for automatic selection by the single strategy request, or pass true/false to override explicitly. Ordinary fused_search keeps its own community default of false and never calls Jev.',
  'constraints was removed as a per-material gate. Keep every research direction and condition in the question/intent; for hard domain limits use site:/-site: or fused_search include_domains/exclude_domains, and verify required document properties by reading.',
  'Read results/valueLevel/selection/diagnostics/usage/warnings. Value 3/4/5 is a reading label, finalScore is not a probability, and targetMet is only quantity. Continue research through concrete doubts under the main Agent instead of assuming missing results prove absence.',
  'Use cursor or saved_result_id with page_size only for saved results; a historical h1: restore is marked and never claims new search, scores or verification.',
]
export function renderAdaptiveSummary(result) {
  const warnings = (result?.warnings ?? []).join('; ')
  if (result?.restoration?.historical) {
    return `adaptive_search: historical snapshot (${result.restoration.originalFormat}${result.restoration.originalSchemaVersion === null ? '' : `, schema v${result.restoration.originalSchemaVersion}`}) — ${result?.pageResults ?? result?.results?.length ?? 0} on this page, ${result?.totalResults ?? 0} saved; original stopReason ${result?.stopReason ?? '?'}; not re-searched, re-screened or re-verified${result?.nextCursor ? '; nextCursor available' : ''}\n${warnings}`
  }
  const selection = result?.selection ?? {}
  return `adaptive_search: ${result?.pageResults ?? result?.results?.length ?? 0} on this page, ${selection.returned ?? 0}/${selection.requested ?? 0} saved — ${result?.stopReason ?? '?'}; ${selection.incomplete ? 'incomplete screening' : 'declared snapshot review finished'}; quantity is not research completion${result?.nextCursor ? '; nextCursor available' : ''}\n${warnings}`
}
export function adaptiveTextContent(result) {
  return [{ type: 'text', text: renderAdaptiveSummary(result) }, { type: 'text', text: JSON.stringify(result) }]
}
