/** Public adaptive response contract, shared with private snapshot validation. */
import * as z from 'zod'

export const adaptiveSearchOutput = {
  savedResultId: z.string().optional(),
  inputSummary: z.object({ question: z.string(), intent: z.string(), keywords: z.array(z.string()), constraints: z.array(z.string()), constraintPolicy: z.literal('explicit_per_material') }).optional(),
  results: z.array(z.object({ url: z.string(), title: z.string(), description: z.string(), tier: z.enum(['focus', 'supporting']).optional(), valueScore: z.number().optional(), directionMatch: z.number().nullable().optional(), kind: z.string().optional(), matches: z.array(z.object({taskId:z.string().nullable(),targetId:z.string().nullable(),canonicalId:z.string().nullable(),valueScore:z.number(),directionMatch:z.number().nullable(),kind:z.string()})).optional() })),
  totalResults: z.number(),
  nextCursor: z.string().nullable(),
  expiresAt: z.string(),
  schemaVersion: z.number().optional(),
  retrievalSufficient: z.boolean().optional().describe('Current deduplicated scores meet the total threshold AND every keyword floor. A retrieval stopping rule, not semantic review, answer completeness or verification.'),
  scopeSummary: z.object({ eligible: z.number(), rejected: z.number(), unknown: z.number() }).optional(),
  convergence: z.object({ method: z.literal('score_threshold_v1'), status: z.enum(['satisfied', 'insufficient']),
    score: z.number().min(0).max(100), totalThreshold: z.number(), keywordTarget: z.number(), keywordFloor: z.number(),
    minimumProgress: z.number(), keywordCount: z.number(),
    points: z.array(z.object({ keyword: z.string(), progress: z.number().min(0).max(1), minimumMet: z.boolean() })),
  }).optional().describe('Deterministic heuristic stopping diagnostic; thresholds are not calibrated probabilities.'),
  finalReview: z.object({ status: z.enum(['not_run', 'not_ready', 'finish', 'continue', 'pending', 'stale']), checks: z.number(),
    verdict: z.enum(['pass', 'not_passed']).nullable().optional(), researchKeyword: z.string().nullable().optional(),
    inputMaterials: z.number().optional(), allMaterialsIncluded: z.boolean().optional() }).optional(),
  reviewSummary: z.object({ collectedRows: z.number(), assessmentUnavailable: z.number(), unreviewed: z.number(), collected: z.number(), withText: z.number(), scopeAssessed: z.number(), scopeSkipped: z.number(),
    constraintsNotPassed: z.number(), qualityAssessed: z.number(), qualityNotPassed: z.number(), admitted: z.number(),
    focus: z.number(), supporting: z.number(), awaitingAdmission: z.number() }).optional(),
  coverageComplete: z.boolean().describe('Deprecated: always false in schemaVersion 3 because answer completeness is not assessed.'),
  keywordProgress: z.array(z.object({
    targetId: z.string(), taskId:z.string().nullable().optional(), canonicalId:z.string().optional(), keyword: z.string(), score: z.number(), ready: z.boolean().optional(),
    status: z.enum(['continue', 'satisfied', 'exhausted', 'pending']).optional(), reason: z.string().optional(),
    distinctEvidence: z.number(), admitted: z.number().optional().describe('Current creditable content/source groups matching this keyword, not the number of admitted documents; may be zero while useful supporting results are retained.'), finalStatus: z.string(),
    progress: z.number().min(0).max(1).optional(), A: z.number().optional(), F: z.number().optional(), R: z.number().optional(),
    missingFacts: z.array(z.string()).optional(),
    factProgress: z.array(z.object({id:z.string(),support:z.number(),covered:z.boolean(),conflicting:z.boolean()})).optional(),
  })).optional(),
  pendingAssessments: z.number().optional(),
  stopReason: z.string(),
  warnings: z.array(z.string()),
}
